#define ANSI_RESET "\x1b[0m"

#define BOLD "\x1b[1m"
#define SOUND "\a"

#define COLOR_BLACK "\x1b[30m"
#define COLOR_RED "\x1b[31m"
#define COLOR_GREEN "\x1b[32m"
#define COLOR_YELLOW "\x1b[33m"
#define COLOR_BLUE "\x1b[34m"
#define COLOR_MAGENTA "\x1b[35m"
#define COLOR_CYAN "\x1b[36m"
#define COLOR_WHITE "\x1b[37m"

#define COLOR_LIGHT_BLACK "\x1b[90m"
#define COLOR_LIGHT_RED "\x1b[91m"
#define COLOR_LIGHT_GREEN "\x1b[92m"
#define COLOR_LIGHT_YELLOW "\x1b[93m"
#define COLOR_LIGHT_BLUE "\x1b[94m"
#define COLOR_LIGHT_MAGENTA "\x1b[95m"
#define COLOR_LIGHT_CYAN "\x1b[96m"
#define COLOR_LIGHT_WHITE "\x1b[97m"

#define BG_BLACK "\x1b[40m"
#define BG_RED "\x1b[41m"
#define BG_GREEN "\x1b[42m"
#define BG_YELLOW "\x1b[43m"
#define BG_BLUE "\x1b[44m"
#define BG_MAGENTA "\x1b[45m"
#define BG_CYAN "\x1b[46m"
#define BG_WHITE "\x1b[47m"

#define BG_LIGHT_BLACK "\x1b[100m"
#define BG_LIGHT_RED "\x1b[101m"
#define BG_LIGHT_GREEN "\x1b[102m"
#define BG_LIGHT_YELLOW "\x1b[103m"
#define BG_LIGHT_BLUE "\x1b[104m"
#define BG_LIGHT_MAGENTA "\x1b[105m"
#define BG_LIGHT_CYAN "\x1b[106m"
#define BG_LIGHT_WHITE "\x1b[107m"
